Predicción dominancia Multilayer Perceptrón

En este fichero se hace una preparación de los datos que se le va a meter a la red nueronal y luego se entrena para que prediga la probabilidad de que los equipos se encuentren en una época de dominancia

De aquí en adelante es una consecución de preparación de los datos para dar como output de la red neuronal cada resultado de cada piloto en cada carrera

In [2]:
import pandas as pd
import numpy as np
from IPython.display import display

circuits=pd.read_csv(r"C:\Users\gonza\OneDrive\Escritorio\Universidad\4to curso\MINERIA DE DATOS\TRABAJO FINAL\BASE DE DATOS\circuits.csv",na_values="\\N")
constructor_results=pd.read_csv(r"C:\Users\gonza\OneDrive\Escritorio\Universidad\4to curso\MINERIA DE DATOS\TRABAJO FINAL\BASE DE DATOS\constructor_results.csv",na_values="\\N")
constructor_standings=pd.read_csv(r"C:\Users\gonza\OneDrive\Escritorio\Universidad\4to curso\MINERIA DE DATOS\TRABAJO FINAL\BASE DE DATOS\constructor_standings.csv",na_values="\\N")
constructors=pd.read_csv(r"C:\Users\gonza\OneDrive\Escritorio\Universidad\4to curso\MINERIA DE DATOS\TRABAJO FINAL\BASE DE DATOS\constructors.csv",na_values="\\N")
driver_standings=pd.read_csv(r"C:\Users\gonza\OneDrive\Escritorio\Universidad\4to curso\MINERIA DE DATOS\TRABAJO FINAL\BASE DE DATOS\driver_standings.csv",na_values="\\N")
drivers=pd.read_csv(r"C:\Users\gonza\OneDrive\Escritorio\Universidad\4to curso\MINERIA DE DATOS\TRABAJO FINAL\BASE DE DATOS\drivers.csv",na_values="\\N")
lap_times=pd.read_csv(r"C:\Users\gonza\OneDrive\Escritorio\Universidad\4to curso\MINERIA DE DATOS\TRABAJO FINAL\BASE DE DATOS\lap_times.csv",na_values="\\N")
pit_stops=pd.read_csv(r"C:\Users\gonza\OneDrive\Escritorio\Universidad\4to curso\MINERIA DE DATOS\TRABAJO FINAL\BASE DE DATOS\pit_stops.csv",na_values="\\N")
qualifying=pd.read_csv(r"C:\Users\gonza\OneDrive\Escritorio\Universidad\4to curso\MINERIA DE DATOS\TRABAJO FINAL\BASE DE DATOS\qualifying.csv",na_values="\\N")
races=pd.read_csv(r"C:\Users\gonza\OneDrive\Escritorio\Universidad\4to curso\MINERIA DE DATOS\TRABAJO FINAL\BASE DE DATOS\races.csv",na_values="\\N")
results=pd.read_csv(r"C:\Users\gonza\OneDrive\Escritorio\Universidad\4to curso\MINERIA DE DATOS\TRABAJO FINAL\BASE DE DATOS\results.csv",na_values="\\N")
seasons=pd.read_csv(r"C:\Users\gonza\OneDrive\Escritorio\Universidad\4to curso\MINERIA DE DATOS\TRABAJO FINAL\BASE DE DATOS\seasons.csv",na_values="\\N")
sprint_results=pd.read_csv(r"C:\Users\gonza\OneDrive\Escritorio\Universidad\4to curso\MINERIA DE DATOS\TRABAJO FINAL\BASE DE DATOS\sprint_results.csv",na_values="\\N")
status=pd.read_csv(r"C:\Users\gonza\OneDrive\Escritorio\Universidad\4to curso\MINERIA DE DATOS\TRABAJO FINAL\BASE DE DATOS\status.csv",na_values="\\N")

In [3]:
from IPython.display import display

prueba=pd.merge(races,circuits, on='circuitId')
display(prueba)
prueba.info()

,raceId,year,round,circuitId,name_x,date,time,url_x,fp1_date,fp1_time,...,sprint_date,sprint_time,circuitRef,name_y,location,country,lat,lng,alt,url_y
0,1,2009,1,1,Australian Grand Prix,2009-03-29,06:00:00,http://en.wikipedia.org/wiki/2009_Australian_G...,NaN,NaN,...,NaN,NaN,albert_park,Albert Park Grand Prix Circuit,Melbourne,Australia,-37.84970,144.96800,10,http://en.wikipedia.org/wiki/Melbourne_Grand_P...
1,2,2009,2,2,Malaysian Grand Prix,2009-04-05,09:00:00,http://en.wikipedia.org/wiki/2009_Malaysian_Gr...,NaN,NaN,...,NaN,NaN,sepang,Sepang International Circuit,Kuala Lumpur,Malaysia,2.76083,101.73800,18,http://en.wikipedia.org/wiki/Sepang_Internatio...
2,3,2009,3,17,Chinese Grand Prix,2009-04-19,07:00:00,http://en.wikipedia.org/wiki/2009_Chinese_Gran...,NaN,NaN,...,NaN,NaN,shanghai,Shanghai International Circuit,Shanghai,China,31.33890,121.22000,5,http://en.wikipedia.org/wiki/Shanghai_Internat...
3,4,2009,4,3,Bahrain Grand Prix,2009-04-26,12:00:00,http://en.wikipedia.org/wiki/2009_Bahrain_Gran...,NaN,NaN,...,NaN,NaN,bahrain,Bahrain International Circuit,Sakhir,Bahrain,26.03250,50.51060,7,http://en.wikipedia.org/wiki/Bahrain_Internati...
4,5,2009,5,4,Spanish Grand Prix,2009-05-10,12:00:00,http://en.wikipedia.org/wiki/2009_Spanish_Gran...,NaN,NaN,...,NaN,NaN,catalunya,Circuit de Barcelona-Catalunya,Montmeló,Spain,41.57000,2.26111,109,http://en.wikipedia.org/wiki/Circuit_de_Barcel...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1120,1140,2024,20,32,Mexico City Grand Prix,2024-10-27,20:00:00,https://en.wikipedia.org/wiki/2024_Mexico_City...,2024-10-25,18:30:00,...,NaN,NaN,rodriguez,Autódromo Hermanos Rodríguez,Mexico City,Mexico,19.40420,-99.09070,2227,http://en.wikipedia.org/wiki/Aut%C3%B3dromo_He...
1121,1141,2024,21,18,São Paulo Grand Prix,2024-11-03,17:00:00,https://en.wikipedia.org/wiki/2024_S%C3%A3o_Pa...,2024-11-01,14:30:00,...,2024-11-02,14:00:00,interlagos,Autódromo José Carlos Pace,São Paulo,Brazil,-23.70360,-46.69970,785,http://en.wikipedia.org/wiki/Aut%C3%B3dromo_Jo...
1122,1142,2024,22,80,Las Vegas Grand Prix,2024-11-23,06:00:00,https://en.wikipedia.org/wiki/2024_Las_Vegas_G...,2024-11-21,02:30:00,...,NaN,NaN,vegas,Las Vegas Strip Street Circuit,Las Vegas,United States,36.11470,-115.17300,642,https://en.wikipedia.org/wiki/Las_Vegas_Grand_...
1123,1143,2024,23,78,Qatar Grand Prix,2024-12-01,17:00:00,https://en.wikipedia.org/wiki/2024_Qatar_Grand...,2024-11-29,13:30:00,...,2024-11-30,13:00:00,losail,Losail International Circuit,Al Daayen,Qatar,25.49000,51.45420,12,http://en.wikipedia.org/wiki/Losail_Internatio...
1124,1144,2024,24,24,Abu Dhabi Grand Prix,2024-12-08,13:00:00,https://en.wikipedia.org/wiki/2024_Abu_Dhabi_G...,2024-12-06,09:30:00,...,NaN,NaN,yas_marina,Yas Marina Circuit,Abu Dhabi,UAE,24.46720,54.60310,3,http://en.wikipedia.org/wiki/Yas_Marina_Circuit

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1125 entries, 0 to 1124
Data columns (total 26 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   raceId       1125 non-null   int64
 1   year         1125 non-null   int64
 2   round        1125 non-null   int64
 3   circuitId    1125 non-null   int64
 4   name_x       1125 non-null   object
 5   date         1125 non-null   object
 6   time         394 non-null    object
 7   url_x        1125 non-null   object
 8   fp1_date     90 non-null     object
 9   fp1_time     68 non-null     object
 10  fp2_date     90 non-null     object
 11  fp2_time     68 non-null     object
 12  fp3_date     72 non-null     object
 13  fp3_time     53 non-null     object
 14  quali_date   90 non-null     object
 15  quali_time   68 non-null     object
 16  sprint_date  18 non-null     object
 17  sprint_time  15 non-null     object
 18  circuitRef   1125 non-null   object
 19  name_y       1125 non-null   object
 20  location     1125 non-null   object
 21  country      1125 non-null   object
 22  lat          1125 non-null   float64
 23  lng          1125 non-null   float64
 24  alt          1125 non-null   int64
 25  url_y        1125 non-null   object
dtypes: float64(2), int64(5), object(19)
memory usage: 228.6+ KB

In [4]:
prueba2=pd.merge(results,prueba, on='raceId')
display(prueba2)
prueba2.info()

,resultId,raceId,driverId,constructorId,number,grid,position,positionText,positionOrder,points,...,sprint_date,sprint_time,circuitRef,name_y,location,country,lat,lng,alt,url_y
0,1,18,1,1,22.0,1,1.0,1,1,10.0,...,NaN,NaN,albert_park,Albert Park Grand Prix Circuit,Melbourne,Australia,-37.8497,144.96800,10,http://en.wikipedia.org/wiki/Melbourne_Grand_P...
1,2,18,2,2,3.0,5,2.0,2,2,8.0,...,NaN,NaN,albert_park,Albert Park Grand Prix Circuit,Melbourne,Australia,-37.8497,144.96800,10,http://en.wikipedia.org/wiki/Melbourne_Grand_P...
2,3,18,3,3,7.0,7,3.0,3,3,6.0,...,NaN,NaN,albert_park,Albert Park Grand Prix Circuit,Melbourne,Australia,-37.8497,144.96800,10,http://en.wikipedia.org/wiki/Melbourne_Grand_P...
3,4,18,4,4,5.0,11,4.0,4,4,5.0,...,NaN,NaN,albert_park,Albert Park Grand Prix Circuit,Melbourne,Australia,-37.8497,144.96800,10,http://en.wikipedia.org/wiki/Melbourne_Grand_P...
4,5,18,5,1,23.0,3,5.0,5,5,4.0,...,NaN,NaN,albert_park,Albert Park Grand Prix Circuit,Melbourne,Australia,-37.8497,144.96800,10,http://en.wikipedia.org/wiki/Melbourne_Grand_P...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26514,26520,1132,839,214,31.0,18,16.0,16,16,0.0,...,NaN,NaN,silverstone,Silverstone Circuit,Silverstone,UK,52.0786,-1.01694,153,http://en.wikipedia.org/wiki/Silverstone_Circuit
26515,26521,1132,815,9,11.0,0,17.0,17,17,0.0,...,NaN,NaN,silverstone,Silverstone Circuit,Silverstone,UK,52.0786,-1.01694,153,http://en.wikipedia.org/wiki/Silverstone_Circuit
26516,26522,1132,855,15,24.0,14,18.0,18,18,0.0,...,NaN,NaN,silverstone,Silverstone Circuit,Silverstone,UK,52.0786,-1.01694,153,http://en.wikipedia.org/wiki/Silverstone_Circuit
26517,26523,1132,847,131,63.0,1,NaN,R,19,0.0,...,NaN,NaN,silverstone,Silverstone Circuit,Silverstone,UK,52.0786,-1.01694,153,http://en.wikipedia.org/wiki/Silverstone_Circuit
26518,26524,1132,842,214,10.0,19,NaN,W,20,0.0,...,NaN,NaN,silverstone,Silverstone Circuit,Silverstone,UK,52.0786,-1.01694,153,http://en.wikipedia.org/wiki/Silverstone_Circuit

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 26519 entries, 0 to 26518
Data columns (total 43 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   resultId         26519 non-null  int64
 1   raceId           26519 non-null  int64
 2   driverId         26519 non-null  int64
 3   constructorId    26519 non-null  int64
 4   number           26513 non-null  float64
 5   grid             26519 non-null  int64
 6   position         15591 non-null  float64
 7   positionText     26519 non-null  object
 8   positionOrder    26519 non-null  int64
 9   points           26519 non-null  float64
 10  laps             26519 non-null  int64
 11  time_x           7533 non-null   object
 12  milliseconds     7533 non-null   float64
 13  fastestLap       8020 non-null   float64
 14  rank             8270 non-null   float64
 15  fastestLapTime   8020 non-null   object
 16  fastestLapSpeed  8020 non-null   float64
 17  statusId         26519 non-null  int64
 18  year             26519 non-null  int64
 19  round            26519 non-null  int64
 20  circuitId        26519 non-null  int64
 21  name_x           26519 non-null  object
 22  date             26519 non-null  object
 23  time_y           8050 non-null   object
 24  url_x            26519 non-null  object
 25  fp1_date         1559 non-null   object
 26  fp1_time         1119 non-null   object
 27  fp2_date         1559 non-null   object
 28  fp2_time         1119 non-null   object
 29  fp3_date         1259 non-null   object
 30  fp3_time         879 non-null    object
 31  quali_date       1559 non-null   object
 32  quali_time       1119 non-null   object
 33  sprint_date      300 non-null    object
 34  sprint_time      240 non-null    object
 35  circuitRef       26519 non-null  object
 36  name_y           26519 non-null  object
 37  location         26519 non-null  object
 38  country          26519 non-null  object
 39  lat              26519 non-null  float64
 40  lng              26519 non-null  float64
 41  alt              26519 non-null  int64
 42  url_y            26519 non-null  object
dtypes: float64(9), int64(12), object(22)
memory usage: 8.7+ MB

In [5]:
prueba3=pit_stops.drop(columns=['stop','lap','time','duration'])

prueba3=(pit_stops.groupby(['raceId', 'driverId'])
    .agg(mean_pit_stop=('milliseconds', 'mean'))  # Calcular la media
    .reset_index())

display(prueba3)
prueba3.info()

      raceId  driverId  mean_pit_stop
0        841         1        23213.0
1        841         2        24046.0
2        841         3        23716.0
3        841         4        24055.0
4        841         5        24865.0
...      ...       ...            ...
5341    1132       848        32076.0
5342    1132       852        29829.0
5343    1132       855        30306.0
5344    1132       857        29370.5
5345    1132       858        31122.5

[5346 rows x 3 columns]

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5346 entries, 0 to 5345
Data columns (total 3 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   raceId         5346 non-null   int64
 1   driverId       5346 non-null   int64
 2   mean_pit_stop  5346 non-null   float64
dtypes: float64(1), int64(2)
memory usage: 125.4 KB

In [6]:

prueba5=races[['raceId','year']]
display(prueba5)

      raceId  year
0          1  2009
1          2  2009
2          3  2009
3          4  2009
4          5  2009
...      ...   ...
1120    1140  2024
1121    1141  2024
1122    1142  2024
1123    1143  2024
1124    1144  2024

[1125 rows x 2 columns]

In [7]:
prueba4=qualifying.drop(columns=['constructorId','number','position'])
prueba4=pd.merge(results,prueba4, on=['raceId','driverId'],how='left')
prueba4=pd.merge(prueba4,prueba3, on=['raceId','driverId'],how='left')
prueba4=pd.merge(prueba4,prueba5, on=['raceId'])
display(prueba4)
prueba4.info()

,resultId,raceId,driverId,constructorId,number,grid,position,positionText,positionOrder,points,...,rank,fastestLapTime,fastestLapSpeed,statusId,qualifyId,q1,q2,q3,mean_pit_stop,year
0,1,18,1,1,22.0,1,1.0,1,1,10.0,...,2.0,1:27.452,218.300,1,1.0,1:26.572,1:25.187,1:26.714,NaN,2008
1,2,18,2,2,3.0,5,2.0,2,2,8.0,...,3.0,1:27.739,217.586,1,5.0,1:25.960,1:25.518,1:27.236,NaN,2008
2,3,18,3,3,7.0,7,3.0,3,3,6.0,...,5.0,1:28.090,216.719,1,7.0,1:26.295,1:26.059,1:28.687,NaN,2008
3,4,18,4,4,5.0,11,4.0,4,4,5.0,...,7.0,1:28.603,215.464,1,12.0,1:26.907,1:26.188,NaN,NaN,2008
4,5,18,5,1,23.0,3,5.0,5,5,4.0,...,1.0,1:27.418,218.385,1,3.0,1:25.664,1:25.452,1:27.079,NaN,2008
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26514,26520,1132,839,214,31.0,18,16.0,16,16,0.0,...,16.0,1:30.875,233.371,12,10309.0,1:34.557,NaN,NaN,28786.50,2024
26515,26521,1132,815,9,11.0,0,17.0,17,17,0.0,...,6.0,1:29.707,236.409,12,10310.0,1:38.348,NaN,NaN,29718.75,2024
26516,26522,1132,855,15,24.0,14,18.0,18,18,0.0,...,17.0,1:31.014,233.014,12,10305.0,1:31.190,1:27.867,NaN,30306.00,2024
26517,26523,1132,847,131,63.0,1,NaN,R,19,0.0,...,19.0,1:31.298,232.289,34,10292.0,1:30.106,1:26.723,1:25.819,32045.00,2024
26518,26524,1132,842,214,10.0,19,NaN,W,20,0.0,...,0.0,NaN,NaN,6,10311.0,1:39.804,NaN,NaN,NaN,2024

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 26519 entries, 0 to 26518
Data columns (total 24 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   resultId         26519 non-null  int64
 1   raceId           26519 non-null  int64
 2   driverId         26519 non-null  int64
 3   constructorId    26519 non-null  int64
 4   number           26513 non-null  float64
 5   grid             26519 non-null  int64
 6   position         15591 non-null  float64
 7   positionText     26519 non-null  object
 8   positionOrder    26519 non-null  int64
 9   points           26519 non-null  float64
 10  laps             26519 non-null  int64
 11  time             7533 non-null   object
 12  milliseconds     7533 non-null   float64
 13  fastestLap       8020 non-null   float64
 14  rank             8270 non-null   float64
 15  fastestLapTime   8020 non-null   object
 16  fastestLapSpeed  8020 non-null   float64
 17  statusId         26519 non-null  int64
 18  qualifyId        10254 non-null  float64
 19  q1               10100 non-null  object
 20  q2               5669 non-null   object
 21  q3               3514 non-null   object
 22  mean_pit_stop    5346 non-null   float64
 23  year             26519 non-null  int64
dtypes: float64(9), int64(9), object(6)
memory usage: 4.9+ MB

In [8]:
prueba4=prueba4.drop(columns=['positionText','time','fastestLap','qualifyId'])

In [9]:
prueba4['fastestLapTime'] = prueba4['fastestLapTime'].apply(str)
prueba4['q1']=prueba4['q1'].apply(str)
prueba4['q2']=prueba4['q2'].apply(str)
prueba4['q3']=prueba4['q3'].apply(str)

def time_to_milliseconds(time_str):
   
    if time_str == 'nan' or time_str == 'None' or time_str.strip() == '':
        return np.nan  # o podrías retornar un valor por defecto, como 0

    parts = time_str.split(':')
    
    if len(parts) == 2:  # Formato 'm:ss.sss'
        minutes, seconds = map(float, parts)
        return int((minutes * 60 + seconds) * 1000)
    
    elif len(parts) == 3:  # Formato 'h:mm:ss.sss'
        hours, minutes, seconds = map(float, parts)
        return int((hours * 3600 + minutes * 60 + seconds) * 1000)
    
    else:
        raise ValueError(f"Formato desconocido para el tiempo: {time_str}")

In [10]:
prueba4['fastestLapTime']=prueba4['fastestLapTime'].apply(time_to_milliseconds)
prueba4['q1']=prueba4['q1'].apply(time_to_milliseconds)
prueba4['q2']=prueba4['q2'].apply(time_to_milliseconds)
prueba4['q3']=prueba4['q3'].apply(time_to_milliseconds)
display(prueba4)

,resultId,raceId,driverId,constructorId,number,grid,position,positionOrder,points,laps,milliseconds,rank,fastestLapTime,fastestLapSpeed,statusId,q1,q2,q3,mean_pit_stop,year
0,1,18,1,1,22.0,1,1.0,1,10.0,58,5690616.0,2.0,87452.0,218.300,1,86572.0,85187.0,86714.0,NaN,2008
1,2,18,2,2,3.0,5,2.0,2,8.0,58,5696094.0,3.0,87739.0,217.586,1,85960.0,85518.0,87236.0,NaN,2008
2,3,18,3,3,7.0,7,3.0,3,6.0,58,5698779.0,5.0,88090.0,216.719,1,86295.0,86059.0,88687.0,NaN,2008
3,4,18,4,4,5.0,11,4.0,4,5.0,58,5707797.0,7.0,88603.0,215.464,1,86907.0,86188.0,NaN,NaN,2008
4,5,18,5,1,23.0,3,5.0,5,4.0,58,5708630.0,1.0,87418.0,218.385,1,85664.0,85452.0,87079.0,NaN,2008
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26514,26520,1132,839,214,31.0,18,16.0,16,0.0,50,NaN,16.0,90875.0,233.371,12,94557.0,NaN,NaN,28786.50,2024
26515,26521,1132,815,9,11.0,0,17.0,17,0.0,50,NaN,6.0,89707.0,236.409,12,98348.0,NaN,NaN,29718.75,2024
26516,26522,1132,855,15,24.0,14,18.0,18,0.0,50,NaN,17.0,91014.0,233.014,12,91190.0,87867.0,NaN,30306.00,2024
26517,26523,1132,847,131,63.0,1,NaN,19,0.0,33,NaN,19.0,91298.0,232.289,34,90106.0,86723.0,85819.0,32045.00,2024
26518,26524,1132,842,214,10.0,19,NaN,20,0.0,0,NaN,0.0,NaN,NaN,6,99804.0,NaN,NaN,NaN,2024

In [11]:
prueba4.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 26519 entries, 0 to 26518
Data columns (total 20 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   resultId         26519 non-null  int64
 1   raceId           26519 non-null  int64
 2   driverId         26519 non-null  int64
 3   constructorId    26519 non-null  int64
 4   number           26513 non-null  float64
 5   grid             26519 non-null  int64
 6   position         15591 non-null  float64
 7   positionOrder    26519 non-null  int64
 8   points           26519 non-null  float64
 9   laps             26519 non-null  int64
 10  milliseconds     7533 non-null   float64
 11  rank             8270 non-null   float64
 12  fastestLapTime   8020 non-null   float64
 13  fastestLapSpeed  8020 non-null   float64
 14  statusId         26519 non-null  int64
 15  q1               10100 non-null  float64
 16  q2               5669 non-null   float64
 17  q3               3514 non-null   float64
 18  mean_pit_stop    5346 non-null   float64
 19  year             26519 non-null  int64
dtypes: float64(11), int64(9)
memory usage: 4.0 MB

In [12]:
prueba4['milliseconds_missing'] = (((~prueba4['statusId'].isin([1,11,12,13,14,15,16,17,18,19]))) & prueba4['milliseconds'].isna()).astype(int)
prueba4['fastestLapTime_missing'] = (((~prueba4['statusId'].isin([1,11,12,13,14,15,16,17,18,19]))) & prueba4['fastestLapTime'].isna()).astype(int)
prueba4['fastestLapSpeed_missing'] = (((~prueba4['statusId'].isin([1,11,12,13,14,15,16,17,18,19]))) & prueba4['fastestLapSpeed'].isna()).astype(int)
prueba4['q1_missing'] = (((~prueba4['statusId'].isin([1,11,12,13,14,15,16,17,18,19]))) & prueba4['q1'].isna()).astype(int)
prueba4['q2_missing'] = prueba4['q2'].isna().astype(int)
prueba4['q3_missing'] = prueba4['q3'].isna().astype(int)
prueba4['mean_pit_stop_missing'] = (((~prueba4['statusId'].isin([1,11,12,13,14,15,16,17,18,19]))) & prueba4['mean_pit_stop'].isna()).astype(int)
prueba4['position_missing'] = (((~prueba4['statusId'].isin([1,11,12,13,14,15,16,17,18,19]))) & prueba4['position'].isna()).astype(int)

Aquí se pasa a imputar los valores faltantes con valores exagerados

In [13]:
# Paso 1: Calcular los valores por grupo (raceId)
grouped = prueba4.groupby('raceId')

# Calcular máximo y media de 'time' por cada 'raceId'
prueba4['max_time_by_race'] = grouped['milliseconds'].transform('max')
prueba4['mean_time_by_race'] = grouped['milliseconds'].transform('mean')
prueba4['max_fastest_lap_by_race'] = grouped['fastestLapTime'].transform('max')
prueba4['mean_fastest_lap_by_race'] = grouped['fastestLapTime'].transform('mean')
prueba4['min_fastest_lap_speed_by_race'] = grouped['fastestLapSpeed'].transform('min')
prueba4['mean_fastest_lap_speed_by_race'] = grouped['fastestLapSpeed'].transform('mean')
prueba4['max_q1_by_race'] = grouped['q1'].transform('max')
prueba4['mean_q1_by_race'] = grouped['q1'].transform('mean')

In [14]:
# Paso 2: Calcular los valores generales
max_time_general = prueba4['milliseconds'].max()
mean_time_general = prueba4['milliseconds'].mean()
max_fastest_lap_general = prueba4['fastestLapTime'].max()
mean_fastest_lap_general = prueba4['fastestLapTime'].mean()
min_lap_speed_general = prueba4['fastestLapSpeed'].min()
mean_lap_speed_general = prueba4['fastestLapSpeed'].mean()
max_q1_general = prueba4['q1'].max()
mean_q1_general = prueba4['q1'].mean()

In [15]:
# Paso 3: Crear una función para imputar valores
def imputar_tiempo(row):
    if row['statusId'] == 11:
        return row['max_time_by_race'] + 0.1 * row['mean_time_by_race']
    elif row['statusId'] == 12:
        return row['max_time_by_race'] + 0.2 * row['mean_time_by_race']
    elif row['statusId'] == 13:
        return row['max_time_by_race'] + 0.3 * row['mean_time_by_race']
    elif row['statusId'] == 14:
        return row['max_time_by_race'] + 0.4 * row['mean_time_by_race']
    elif row['statusId'] == 15:
        return row['max_time_by_race'] + 0.5 * row['mean_time_by_race']
    elif row['statusId'] == 16:
        return row['max_time_by_race'] + 0.6 * row['mean_time_by_race']
    elif row['statusId'] == 17:
        return row['max_time_by_race'] + 0.7 * row['mean_time_by_race']
    elif row['statusId'] == 18:
        return row['max_time_by_race'] + 0.8 * row['mean_time_by_race']
    elif row['statusId'] == 19:
        return row['max_time_by_race'] + 0.9 * row['mean_time_by_race']
    elif row['statusId'] != 1 and pd.isnull(row['milliseconds']):
        return max_time_general + mean_time_general
    elif pd.isnull(row['milliseconds']):
        return max_time_general + mean_time_general
    else:
        return row['milliseconds']  # Dejar el valor original si no cumple las condiciones

# Paso 3: Crear una función para imputar valores
def imputar_vuelta_rapida(row):
    if pd.isnull(row['fastestLapTime']) and pd.notna(row['max_fastest_lap_by_race']):
        return row['max_fastest_lap_by_race'] + row['mean_fastest_lap_by_race']
    elif pd.isnull(row['fastestLapTime']):
        return max_fastest_lap_general + mean_fastest_lap_general
    else:
        return row['fastestLapTime']  # Dejar el valor original si no cumple las condiciones

# Paso 3: Crear una función para imputar valores
def imputar_velocidad(row):
    if pd.isnull(row['fastestLapSpeed']) and pd.notna(row['min_fastest_lap_speed_by_race']):
        return row['min_fastest_lap_speed_by_race'] - row['mean_fastest_lap_speed_by_race']
    elif pd.isnull(row['fastestLapSpeed']):
        return min_lap_speed_general + mean_lap_speed_general
    else:
        return row['fastestLapSpeed']  # Dejar el valor original si no cumple las condiciones

def imputar_q1(row):
    if pd.isnull(row['q1']):
        return max_q1_general + mean_q1_general
    else:
        return row['q1']  # Dejar el valor original si no cumple las condiciones
    
def imputar_q2(row):
    if pd.isnull(row['q2']) and pd.notna(row['max_q1_by_race']):
        return row['max_q1_by_race'] + row['mean_q1_by_race']
    elif pd.isnull(row['q2']):
        return max_q1_general + mean_q1_general
    else:
        return row['q2']  # Dejar el valor original si no cumple las condiciones
    
def imputar_q3(row):
    if pd.isnull(row['q3']) and pd.notna(row['max_q1_by_race']):
        return row['max_q1_by_race'] + row['mean_q1_by_race']
    elif pd.isnull(row['q3']):
        return max_q1_general + mean_q1_general
    else:
        return row['q3']  # Dejar el valor original si no cumple las condiciones

In [16]:
# Paso 4: Aplicar la función
prueba4['milliseconds'] = prueba4.apply(imputar_tiempo, axis=1)
prueba4['fastestLapTime']=prueba4.apply(imputar_vuelta_rapida, axis=1)
prueba4['fastestLapSpeed']=prueba4.apply(imputar_velocidad,axis=1)
prueba4['q1']=prueba4.apply(imputar_q1,axis=1)
prueba4['q2']=prueba4.apply(imputar_q2,axis=1)
prueba4['q3']=prueba4.apply(imputar_q3,axis=1)

In [17]:
# Paso 5: Eliminar columnas intermedias si ya no son necesarias
prueba4.drop(['max_time_by_race', 'mean_time_by_race','max_fastest_lap_by_race','mean_fastest_lap_by_race',
 'min_fastest_lap_speed_by_race','mean_fastest_lap_speed_by_race','max_q1_by_race','mean_q1_by_race','number','rank'], axis=1, inplace=True)

In [18]:
prueba4['mean_pit_stop'] = prueba4['mean_pit_stop'].fillna(prueba4['mean_pit_stop'].max())
prueba4['position'] = prueba4['position'].fillna(30)
display(prueba4)

,resultId,raceId,driverId,constructorId,grid,position,positionOrder,points,laps,milliseconds,...,mean_pit_stop,year,milliseconds_missing,fastestLapTime_missing,fastestLapSpeed_missing,q1_missing,q2_missing,q3_missing,mean_pit_stop_missing,position_missing
0,1,18,1,1,1,1.0,1,10.0,58,5.690616e+06,...,3055732.00,2008,0,0,0,0,0,0,0,0
1,2,18,2,2,5,2.0,2,8.0,58,5.696094e+06,...,3055732.00,2008,0,0,0,0,0,0,0,0
2,3,18,3,3,7,3.0,3,6.0,58,5.698779e+06,...,3055732.00,2008,0,0,0,0,0,0,0,0
3,4,18,4,4,11,4.0,4,5.0,58,5.707797e+06,...,3055732.00,2008,0,0,0,0,0,1,0,0
4,5,18,5,1,3,5.0,5,4.0,58,5.708630e+06,...,3055732.00,2008,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26514,26520,1132,839,214,18,16.0,16,0.0,50,6.036148e+06,...,28786.50,2024,0,0,0,0,1,1,0,0
26515,26521,1132,815,9,0,17.0,17,0.0,50,6.036148e+06,...,29718.75,2024,0,0,0,0,1,1,0,0
26516,26522,1132,855,15,14,18.0,18,0.0,50,6.036148e+06,...,30306.00,2024,0,0,0,0,0,1,0,0
26517,26523,1132,847,131,1,30.0,19,0.0,33,2.129926e+07,...,32045.00,2024,1,0,0,0,0,0,0,1
26518,26524,1132,842,214,19,30.0,20,0.0,0,2.129926e+07,...,3055732.00,2024,1,1,1,0,1,1,1,1

In [19]:
faltantes = prueba4.isna().sum()

# Mostrar las columnas con valores faltantes
print(faltantes[faltantes > 0])

Series([], dtype: int64)

In [20]:
prueba4.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 26519 entries, 0 to 26518
Data columns (total 26 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   resultId                 26519 non-null  int64
 1   raceId                   26519 non-null  int64
 2   driverId                 26519 non-null  int64
 3   constructorId            26519 non-null  int64
 4   grid                     26519 non-null  int64
 5   position                 26519 non-null  float64
 6   positionOrder            26519 non-null  int64
 7   points                   26519 non-null  float64
 8   laps                     26519 non-null  int64
 9   milliseconds             26519 non-null  float64
 10  fastestLapTime           26519 non-null  float64
 11  fastestLapSpeed          26519 non-null  float64
 12  statusId                 26519 non-null  int64
 13  q1                       26519 non-null  float64
 14  q2                       26519 non-null  float64
 15  q3                       26519 non-null  float64
 16  mean_pit_stop            26519 non-null  float64
 17  year                     26519 non-null  int64
 18  milliseconds_missing     26519 non-null  int64
 19  fastestLapTime_missing   26519 non-null  int64
 20  fastestLapSpeed_missing  26519 non-null  int64
 21  q1_missing               26519 non-null  int64
 22  q2_missing               26519 non-null  int64
 23  q3_missing               26519 non-null  int64
 24  mean_pit_stop_missing    26519 non-null  int64
 25  position_missing         26519 non-null  int64
dtypes: float64(9), int64(17)
memory usage: 5.3 MB

Estandarizamos nuestro dataframe

In [21]:
from sklearn.preprocessing import MinMaxScaler
no_estandarizar=['resultId','raceId','driverId','constructorId','grid','position','positionOrder','points','laps','StatusId','year','milliseconds_missing',
                 'fastestLapTime_missing','fastestLapSpeed_missing','q1_missing','q2_missing','q3_missing','mean_pit_stop_missing','position_missing']
si_estandarizar = [col for col in prueba4.columns if col not in no_estandarizar]
scaler = MinMaxScaler(feature_range=(0,40))
prueba4[si_estandarizar]= scaler.fit_transform(prueba4[si_estandarizar])

Definimos como entrenamiento hasta 2020 y como test desde 2021

In [22]:
train=prueba4[prueba4['year']<2021]
test=prueba4[prueba4['year']>=2021]

Definimos como épocas de dominancias las tres épocas de dominancia más grandes de la competición

In [23]:
condicion1 = (train['year'].between(2014,2020)) & (train['constructorId'] == 131) 
condicion2 = (train['year'].between(2000,2004)) & (train['constructorId'] == 6) 
condicion3 = (train['year'].between(1992,1997)) & (train['constructorId'] == 3) 
condicion= condicion1 | condicion2 | condicion3
train['dominancia']=condicion.astype(int)

C:\Users\gonza\AppData\Local\Temp\ipykernel_27900\4240786890.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  train['dominancia']=condicion.astype(int)

In [24]:
prueba4.to_csv(r"C:\Users\gonza\OneDrive\Escritorio\Universidad\4to curso\MINERIA DE DATOS\TRABAJO FINAL\pruebaMLP.csv",index=False)

In [25]:
print(prueba4['grid'].isnull().sum())

0

A continuación definimos la red para poder predecir la probabilidad

In [ ]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.optimizers import Adam
from sklearn.model_selection import train_test_split

identificadores=['resultId','driverId','constructorId']
X_train_2020=train.drop(columns=identificadores,axis=1)
X_train_2020=X_train_2020.drop('dominancia',axis=1)
y_train_2020=train['dominancia']
test2=test.drop(columns=identificadores)

# Definir parámetros
batch_size = 64  # Tamaño del batch
epochs = 50  # Número de épocas
learning_rate = 0.001  # Tasa de aprendizaje



X_train, X_val, y_train, y_val = train_test_split(X_train_2020, y_train_2020, test_size=0.2, random_state=42)

# Definir la arquitectura de la red neuronal (Perceptron Multicapa)
model = Sequential()

# Capa de entrada + primera capa oculta
model.add(Dense(units=64, activation='relu', input_dim=X_train.shape[1]))

# Capa oculta adicional
model.add(Dense(units=32, activation='relu'))


# Capa de salida
model.add(Dense(units=1, activation='sigmoid'))  # Usamos sigmoid porque es clasificación binaria

# Compilación del modelo
model.compile(optimizer=Adam(learning_rate=learning_rate), loss='binary_crossentropy', metrics=['accuracy'])

# Resumen del modelo para verificar la arquitectura
model.summary()

# Entrenamiento del modelo con validación
history = model.fit(X_train, y_train, epochs=epochs, batch_size=batch_size, validation_data=(X_val, y_val))

# Evaluación del modelo en el conjunto de validación
val_loss, val_accuracy = model.evaluate(X_val, y_val)
print(f"Validation Loss: {val_loss}")
print(f"Validation Accuracy: {val_accuracy}")



# Predicción de la probabilidad de que cada equipo esté en una era de dominancia
predictions = model.predict(test2)

# Ahora, agrupamos las predicciones por equipo (asumiendo que 'teamId' es la columna que identifica a los equipos)
test['predicted_prob'] = predictions

# Calculamos la probabilidad media para cada equipo a través de sus carreras en 2021
team_probabilities = test.groupby('constructorId')['predicted_prob'].mean()

# Crear un diccionario de mapeo desde la tabla 'constructors'
id_to_name = dict(zip(constructors['constructorId'], constructors['name']))

# Mapear los nombres de los equipos en lugar de sus IDs
team_probabilities_named = {id_to_name[team_id]: prob for team_id, prob in team_probabilities.items()}

# Mostrar las probabilidades con los nombres de los equipos
for team_name, prob in team_probabilities_named.items():
    print(f"Probabilidad de dominancia para el equipo {team_name} en toda la época (2021 en adelante): {prob:.4f}")

c:\Users\gonza\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 64)             │         1,536 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 32)             │         2,080 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 1)              │            33 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 3,649 (14.25 KB)

 Trainable params: 3,649 (14.25 KB)

 Non-trainable params: 0 (0.00 B)

Epoch 1/50
312/312 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.9554 - loss: 1.2112 - val_accuracy: 0.4493 - val_loss: 1.8288
Epoch 2/50
312/312 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.9568 - loss: 0.8143 - val_accuracy: 0.9748 - val_loss: 0.0866
Epoch 3/50
312/312 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.9603 - loss: 0.2164 - val_accuracy: 0.9778 - val_loss: 0.0773
Epoch 4/50
312/312 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.9632 - loss: 0.2482 - val_accuracy: 0.9752 - val_loss: 0.2717
Epoch 5/50
312/312 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.9631 - loss: 0.5140 - val_accuracy: 0.8051 - val_loss: 0.7134
Epoch 6/50
312/312 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.9587 - loss: 0.4302 - val_accuracy: 0.9700 - val_loss: 0.0926
Epoch 7/50
312/312 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.9664 - loss: 0.2107 - val_accuracy: 0.9085 - val_loss: 0.2811
Epoch 8/50
312/312 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.9630 - loss: 0.2398 - val_accuracy: 0.9752 - val_loss: 0.3598
Epoch 9/50
312/312 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.9709 - loss: 0.1393 - val_accuracy: 0.9625 - val_loss: 0.1238
Epoch 10/50
312/312 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.9680 - loss: 0.1931 - val_accuracy: 0.9515 - val_loss: 0.1797
Epoch 11/50
312/312 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.9625 - loss: 0.1876 - val_accuracy: 0.8744 - val_loss: 0.5445
Epoch 12/50
312/312 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.9634 - loss: 0.2367 - val_accuracy: 0.9752 - val_loss: 0.1259
Epoch 13/50
312/312 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.9702 - loss: 0.1756 - val_accuracy: 0.9333 - val_loss: 0.1880
Epoch 14/50
312/312 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.9655 - loss: 0.1891 - val_accuracy: 0.9750 - val_loss: 0.0811
Epoch 15/50
312/312 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.9674 - loss: 0.1620 - val_accuracy: 0.9776 - val_loss: 0.0914
Epoch 16/50
312/312 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.9680 - loss: 0.1370 - val_accuracy: 0.9780 - val_loss: 0.1813
Epoch 17/50
312/312 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.9661 - loss: 0.1890 - val_accuracy: 0.9667 - val_loss: 0.1212
Epoch 18/50
312/312 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.9664 - loss: 0.1391 - val_accuracy: 0.9774 - val_loss: 0.0703
Epoch 19/50
312/312 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.9657 - loss: 0.1624 - val_accuracy: 0.9768 - val_loss: 0.0730
Epoch 20/50
312/312 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.9651 - loss: 0.1596 - val_accuracy: 0.9457 - val_loss: 0.1945
Epoch 21/50
312/312 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.9677 - loss: 0.1750 - val_accuracy: 0.9561 - val_loss: 0.1206
Epoch 22/50
312/312 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.9686 - loss: 0.1257 - val_accuracy: 0.9567 - val_loss: 0.1178
Epoch 23/50
312/312 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.9693 - loss: 0.1190 - val_accuracy: 0.9752 - val_loss: 0.1479
Epoch 24/50
312/312 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.9684 - loss: 0.1568 - val_accuracy: 0.9383 - val_loss: 0.1592
Epoch 25/50
312/312 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.9657 - loss: 0.2145 - val_accuracy: 0.9641 - val_loss: 0.0906
Epoch 26/50
312/312 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.9680 - loss: 0.1188 - val_accuracy: 0.8768 - val_loss: 0.4108
Epoch 27/50
312/312 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.9680 - loss: 0.1442 - val_accuracy: 0.9752 - val_loss: 0.1513
Epoch 28/50
312/312 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.9684 - loss: 0.1494 - val_accuracy: 0.9756 - val_loss: 0.1165
Epoch 29/50
312/312 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.9706 - loss: 0.0942 - val_accuracy: 0.9782 - val_loss: 0.0722
Epoch 30/50
312/312 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.9694 - loss: 0.1149 - val_accuracy: 0.9752 - val_loss: 0.2800
Epoch 31/50
312/312 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.9721 - loss: 0.1129 - val_accuracy: 0.9615 - val_loss: 0.0959
Epoch 32/50
312/312 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.9713 - loss: 0.1011 - val_accuracy: 0.9720 - val_loss: 0.0663
Epoch 33/50
312/312 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.9716 - loss: 0.0981 - val_accuracy: 0.9720 - val_loss: 0.0683
Epoch 34/50
312/312 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.9718 - loss: 0.1052 - val_accuracy: 0.9629 - val_loss: 0.0994
Epoch 35/50
312/312 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.9711 - loss: 0.1057 - val_accuracy: 0.9752 - val_loss: 0.1055
Epoch 36/50
312/312 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.9695 - loss: 0.1003 - val_accuracy: 0.9489 - val_loss: 0.1476
Epoch 37/50
312/312 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.9729 - loss: 0.1013 - val_accuracy: 0.9784 - val_loss: 0.0529
Epoch 38/50
312/312 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.9689 - loss: 0.0920 - val_accuracy: 0.9756 - val_loss: 0.0597
Epoch 39/50
312/312 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.9741 - loss: 0.0736 - val_accuracy: 0.9770 - val_loss: 0.0555
Epoch 40/50
312/312 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.9689 - loss: 0.1563 - val_accuracy: 0.9764 - val_loss: 0.0620
Epoch 41/50
312/312 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.9702 - loss: 0.0954 - val_accuracy: 0.9752 - val_loss: 0.1184
Epoch 42/50
312/312 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.9687 - loss: 0.0973 - val_accuracy: 0.9776 - val_loss: 0.0764
Epoch 43/50
312/312 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.9704 - loss: 0.1116 - val_accuracy: 0.9794 - val_loss: 0.0516
Epoch 44/50
312/312 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.9703 - loss: 0.0866 - val_accuracy: 0.9776 - val_loss: 0.0530
Epoch 45/50
312/312 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.9735 - loss: 0.0764 - val_accuracy: 0.9776 - val_loss: 0.0668
Epoch 46/50
312/312 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.9706 - loss: 0.0907 - val_accuracy: 0.9732 - val_loss: 0.0699
Epoch 47/50
312/312 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.9704 - loss: 0.0888 - val_accuracy: 0.9780 - val_loss: 0.0572
Epoch 48/50
312/312 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.9724 - loss: 0.0737 - val_accuracy: 0.9752 - val_loss: 0.0689
Epoch 49/50
312/312 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.9751 - loss: 0.0670 - val_accuracy: 0.9784 - val_loss: 0.0584
Epoch 50/50
312/312 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.9740 - loss: 0.0752 - val_accuracy: 0.9780 - val_loss: 0.0576
156/156 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.9793 - loss: 0.0557
Validation Loss: 0.05758117884397507
Validation Accuracy: 0.9779647588729858
49/49 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
Probabilidad de dominancia para el equipo McLaren en toda la época (2021 en adelante): 0.3923
Probabilidad de dominancia para el equipo Williams en toda la época (2021 en adelante): 0.0884
Probabilidad de dominancia para el equipo Ferrari en toda la época (2021 en adelante): 0.5892
Probabilidad de dominancia para el equipo Red Bull en toda la época (2021 en adelante): 0.7432
Probabilidad de dominancia para el equipo Sauber en toda la época (2021 en adelante): 0.1292
Probabilidad de dominancia para el equipo Alfa Romeo en toda la época (2021 en adelante): 0.0995
Probabilidad de dominancia para el equipo Aston Martin en toda la época (2021 en adelante): 0.2434
Probabilidad de dominancia para el equipo Mercedes en toda la época (2021 en adelante): 0.6335
Probabilidad de dominancia para el equipo Haas F1 Team en toda la época (2021 en adelante): 0.1042
Probabilidad de dominancia para el equipo AlphaTauri en toda la época (2021 en adelante): 0.1543
Probabilidad de dominancia para el equipo Alpine F1 Team en toda la época (2021 en adelante): 0.2012
Probabilidad de dominancia para el equipo RB F1 Team en toda la época (2021 en adelante): 0.2326
Probabilidad de dominancia para el equipo 1 en toda la época (2021 en adelante): 0.3923
Probabilidad de dominancia para el equipo 3 en toda la época (2021 en adelante): 0.0884
Probabilidad de dominancia para el equipo 6 en toda la época (2021 en adelante): 0.5892
Probabilidad de dominancia para el equipo 9 en toda la época (2021 en adelante): 0.7432
Probabilidad de dominancia para el equipo 15 en toda la época (2021 en adelante): 0.1292
Probabilidad de dominancia para el equipo 51 en toda la época (2021 en adelante): 0.0995
Probabilidad de dominancia para el equipo 117 en toda la época (2021 en adelante): 0.2434
Probabilidad de dominancia para el equipo 131 en toda la época (2021 en adelante): 0.6335
Probabilidad de dominancia para el equipo 210 en toda la época (2021 en adelante): 0.1042
Probabilidad de dominancia para el equipo 213 en toda la época (2021 en adelante): 0.1543
Probabilidad de dominancia para el equipo 214 en toda la época (2021 en adelante): 0.2012
Probabilidad de dominancia para el equipo 215 en toda la época (2021 en adelante): 0.2326

C:\Users\gonza\AppData\Local\Temp\ipykernel_27900\1361340852.py:54: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test['predicted_prob'] = predictions